# Generated by Django 5.2.3 on 2025-06-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_category_is_active_category_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_gluten_free',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegan',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_vegetarian',
        ),
    ]
