# Generated by Django 5.2.3 on 2025-06-21 07:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_counter_items'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the tax', max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate as percentage (e.g., 15.00 for 15%)', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Optional description of the tax', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vat_taxes', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'VAT Tax',
                'verbose_name_plural': 'VAT Taxes',
                'ordering': ['name'],
            },
        ),
    ]
